runtime: nodejs10

includes:
  -env_variables.yaml 

entrypoint: node ./server/server.js

env_variables:
  CLOUD_INSTANCE: recipe-app-database-271816:us-central1:recipe-app-database

instance_class: F2
resources:
  memory_gb: 0.25